server:
  port: 8080
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.243.140.63:1521:wolfdb
    username: wolf
    password: wolf
#    url: jdbc:oracle:thin:@10.253.2.113:49161:XE
#    username: system
#    password: oracle
    max-idle: 10
    max-wait: 10000
    min-idle: 10
    initial-size: 10